import { ethers, network, artifacts } from "hardhat";
import { writeFileSync, mkdirSync } from "fs";
import { resolve } from "path";

async function main() {
  const [deployer] = await ethers.getSigners();
  console.log(`Network: ${network.name}`);
  console.log(`Deployer: ${deployer.address}`);

  const Factory = await ethers.getContractFactory("EasyRideEscrow");
  const escrow = await Factory.deploy();
  await escrow.waitForDeployment();

  const address = await escrow.getAddress();
  const tx = escrow.deploymentTransaction();
  console.log(`EasyRideEscrow deployed at: ${address}`);
  if (tx) console.log(`Deploy tx: ${tx.hash}`);
  if (network.name === "arc") {
    console.log(`Explorer: https://testnet.arcscan.app/address/${address}`);
  }

  // 1) Save deployment record (per-network).
  const deploymentsDir = resolve(__dirname, "..", "deployments");
  mkdirSync(deploymentsDir, { recursive: true });
  writeFileSync(
    resolve(deploymentsDir, `${network.name}.json`),
    JSON.stringify(
      { address, network: network.name, chainId: Number(network.config.chainId ?? 0), txHash: tx?.hash ?? null },
      null,
      2,
    ),
  );

  // 2) Export ABI + address into the Next app (so it never imports Hardhat).
  const artifact = await artifacts.readArtifact("EasyRideEscrow");
  const appDir = resolve(__dirname, "..", "..", "src", "lib", "contracts");
  mkdirSync(appDir, { recursive: true });
  const ts =
    `// AUTO-GENERATED by contracts-hardhat/scripts/deploy.ts — do not edit by hand.\n` +
    `export const EASY_RIDE_ESCROW_ADDRESS = ${JSON.stringify(address)} as const;\n` +
    `export const EASY_RIDE_ESCROW_CHAIN_ID = ${Number(network.config.chainId ?? 0)};\n` +
    `export const EASY_RIDE_ESCROW_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;\n`;
  writeFileSync(resolve(appDir, "easyRideEscrow.ts"), ts);
  console.log(`ABI exported to src/lib/contracts/easyRideEscrow.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
